# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'FirebaseProject' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Required by RNFirebase
  pod 'Firebase/Core', '~> 5.3.0'

  # Pods for FirebaseProject
  pod 'Firebase/Auth', '~> 5.3.0'

  target 'FirebaseProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
